name: Run Checks

on:
  - pull_request

jobs:
  run-checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
        with:
          version: latest
      - uses: actions/setup-node@v7
        with:
          node-version: lts/*
          cache: pnpm
      - name: Install dependencies
        run: |
          pnpm config set only-built-dependencies --json '["esbuild", "vue-demi"]'
          pnpm install --frozen-lockfile
      - run: pnpm lint
      - run: pnpm test
      - run: npx nuxi typecheck
